version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker-creds/username
    DOCKER_REGISTRY_PASSWORD: /docker-creds/password

phases:
  install:
    runtime-versions:
      python: 3.12

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin docker.io

  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_USERNAME/codepipeline-demo:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/codepipeline-demo:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
